# Generated by Django 5.2.3 on 2025-06-23 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrondissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroArrondissement', models.CharField(max_length=50, unique=True)),
                ('NombreElecteursInscrits', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Electeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
                ('DateNaissance', models.DateField()),
                ('LieuNaissance', models.CharField(max_length=100)),
                ('NumCIN', models.CharField(max_length=50, unique=True)),
                ('Adresse', models.TextField()),
                ('Profession', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='electeurs/images/')),
                ('NumeroTel', models.CharField(max_length=20)),
                ('IdArrondissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electeurs', to='electeurs.arrondissement')),
            ],
            options={
                'verbose_name': 'Électeur',
                'verbose_name_plural': 'Électeurs',
            },
        ),
    ]
