# Generated by Django 5.2.3 on 2025-06-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electeurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electeur',
            name='NumCIN',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
